CREATE TABLE IF NOT EXISTS `voluntrack`.`USER_PROJECT` (
  `USER_ID` INT UNSIGNED NOT NULL,
  `PROJECT_ID` INT UNSIGNED NOT NULL,
  `PROJECT_START_DATE_TIME` DATETIME(0) NOT NULL,
  `PROJECT_END_DATE_TIME` DATETIME(0) NOT NULL,
  INDEX `PROJECT_ID_idx` (`PROJECT_ID` ASC, `USER_ID` ASC),
  INDEX `User_id _idx` (`USER_ID` ASC),
  CONSTRAINT `User_id `
    FOREIGN KEY (`USER_ID`)
    REFERENCES `mydb`.`USER` (`USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PROJECT_ID`
    FOREIGN KEY (`PROJECT_ID` , `USER_ID`)
    REFERENCES `mydb`.`PROJECT` (`Project_Name` , `Project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
